# SmartIntern AI - Configuration principale
spring.application.name=SmartIntern AI

# MySQL DataSource
spring.datasource.url=jdbc:mysql://localhost:3306/smartintern_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=SmartInternAI2026SecretKeyForJWTTokenGeneration256BitsMinimum
jwt.expiration=86400000

# SQL Init
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true


server.port=8081