# SmartIntern AI - Profil Dev Local
spring.datasource.url=jdbc:mysql://localhost:3306/smartintern_dev?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root

# Debug
spring.jpa.show-sql=true
logging.level.com.smartintern=DEBUG
logging.level.org.springframework.security=DEBUG
